### ISSUE TITLE
Design docs cache is not cleared when a database is erased

### ISSUE THREAD

**Issue by ellneal** [couchrest/couchrest_model#212]
I'm not sure what the best way to solve this problem is so I was hoping to start a dialogue about it, and then I'm happy to implement the fix once decided.

The problem arises when a database is erased and recreated with cached checksums for the design docs (where `auto_update` is enabled). When the database is recreated and a view is accessed, `couchrest_model` checks its cache and believes the views are there so doesn't save them to the new _empty_ database, leading to a 404 response. 2 things I'm considering as the best options are:

1) Always erase the cache and retry if accessing a view returns a 404.
2) Implement some kind of observer pattern that informs the `Design` class when a database is erased.

**Comment by ktaragorn** [comment]
This is fixed in #216
